# Data Collecting

In [1]:
import pandas as pd

df = pd.read_excel('../data/raw/Tweet.xlsx', sheet_name='SocialMedia (1)')

In [2]:
df.head()

,Tweet,id,time,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,...,hashtag clicks,detail expands,permalink clicks,app opens,app installs,follows,email tweet,dial phone,media views,media engagements
0,id ligula suspendisse ornare consequat lectus ...,6672567125560790,2020-06-30 21:09 +0000,365.0,4.0,0.010959,0.0,0,1.0,2.0,...,0,1,0,0,0,0,0,0,0.0,0.0
1,euismod scelerisque quam turpis adipiscing lor...,8265456713789040,2020-06-30 17:14 +0000,184.0,2.0,0.010870,0.0,0,2.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
2,leo rhoncus sed vestibulum sit amet cursus id ...,281117346800427,2020-06-30 16:59 +0000,2644.0,46.0,0.017398,1.0,1,17.0,0.0,...,0,23,0,0,0,0,0,0,354.0,1.0
3,aenean lectus pellentesque eget nunc donec qui...,7758025943576750,2020-06-30 13:55 +0000,301.0,3.0,0.009967,0.0,1,2.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0
4,sed accumsan felis ut at dolor quis odio conse...,6131837006729570,2020-06-30 12:13 +0000,528.0,0.0,0.000000,0.0,0,0.0,0.0,...,0,0,0,0,0,0,0,0,0.0,0.0

In [3]:
df.shape

(1181, 21)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1181 entries, 0 to 1180
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Tweet                1181 non-null   object
 1   id                   1181 non-null   int64
 2   time                 1181 non-null   object
 3   impressions          1179 non-null   float64
 4   engagements          1179 non-null   float64
 5   engagement rate      1179 non-null   float64
 6   retweets             1180 non-null   float64
 7   replies              1181 non-null   int64
 8   likes                1181 non-null   float64
 9   user profile clicks  1181 non-null   float64
 10  url clicks           1181 non-null   int64
 11  hashtag clicks       1181 non-null   int64
 12  detail expands       1181 non-null   int64
 13  permalink clicks     1181 non-null   int64
 14  app opens            1181 non-null   int64
 15  app installs         1181 non-null   int64
 16  follows              1181 non-null   int64
 17  email tweet          1181 non-null   int64
 18  dial phone           1181 non-null   int64
 19  media views          1169 non-null   float64
 20  media engagements    1168 non-null   float64
dtypes: float64(8), int64(11), object(2)
memory usage: 193.9+ KB

In [5]:
df.describe()

,id,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,url clicks,hashtag clicks,detail expands,permalink clicks,app opens,app installs,follows,email tweet,dial phone,media views,media engagements
count,1.181000e+03,1179.000000,1179.000000,1179.000000,1180.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.000000,1181.0,1181.000000,1181.000000,1169.000000,1168.000000
mean,4.869653e+15,773.282124,78.285838,0.066514,0.937288,1.417443,6.932271,2.176127,3.022862,0.259949,13.128704,0.000847,0.002540,0.000847,0.0,1.738357,0.462320,76.197605,52.671233
std,2.912818e+15,4679.852991,1578.955143,0.534397,12.906901,14.395244,72.879727,20.382764,19.655602,1.610662,136.196470,0.029099,0.065045,0.029099,0.0,41.171964,11.438397,1363.459588,1361.448226
min,4.837987e+12,0.010899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
25%,2.345457e+15,163.000000,3.000000,0.012206,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
50%,4.789145e+15,295.000000,6.000000,0.023392,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
75%,7.465578e+15,704.000000,18.000000,0.043011,0.000000,1.000000,5.000000,1.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,30.000000,1.000000
max,9.987611e+15,156685.000000,54098.000000,15.000000,402.000000,483.000000,2487.000000,641.000000,428.000000,41.000000,4024.000000,1.000000,2.000000,1.000000,0.0,1341.000000,381.000000,46489.000000,46489.000000

In [6]:
df.isnull().sum()

Tweet                   0
id                      0
time                    0
impressions             2
engagements             2
engagement rate         2
retweets                1
replies                 0
likes                   0
user profile clicks     0
url clicks              0
hashtag clicks          0
detail expands          0
permalink clicks        0
app opens               0
app installs            0
follows                 0
email tweet             0
dial phone              0
media views            12
media engagements      13
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['replies'].value_counts().head(10)

replies
0     609
1     398
2      94
3      31
4      13
5       7
6       5
10      4
8       3
9       3
Name: count, dtype: int64

In [9]:
df['retweets'].value_counts().head(10)

retweets
0.0      1034
1.0        72
2.0        21
4.0        15
3.0        11
5.0         9
15.0        3
8.0         2
6.0         2
165.0       1
Name: count, dtype: int64

In [10]:
df['app opens'].value_counts()

app opens
0    1179
1       1
2       1
Name: count, dtype: int64

In [11]:
df['app installs'].value_counts()

app installs
0    1180
1       1
Name: count, dtype: int64

# Data Cleaning

## Issue 1: Corrupted rows — bare numbers in the `time` column

In [12]:
corrupted_mask = pd.to_numeric(df['time'], errors='coerce').notna()
df[corrupted_mask][['Tweet', 'time', 'impressions', 'engagements', 'engagement rate']]

,Tweet,time,impressions,engagements,engagement rate
105,vestibulum rutrum rutrum neque aenean auctor g...,304,0.061340,16.000000,15.0
332,ridiculus mus etiam vel augue vestibulum rutru...,76,0.050398,9.000000,0.0
338,in porttitor pede justo eu massa donec dapibus...,28,0.058455,0.000000,2.0
364,eget tempus vel pede morbi porttitor lorem id ...,45,0.060484,0.000000,1.0
376,in tempus sit amet sem fusce consequat nulla n...,495,0.081575,3.000000,9.0
547,semper est quam pharetra magna ac consequat me...,3,0.011494,0.000000,0.0
563,sollicitudin ut suscipit a feugiat et eros ves...,4,0.010899,0.000000,0.0
711,etiam vel augue vestibulum rutrum rutrum neque...,3,0.024590,1.000000,1.0
786,magna vulputate luctus cum sociis natoque pena...,284,0.048144,8.000000,1.0
848,nulla ultrices aliquet maecenas leo odio condi...,405,1.000000,0.002469,0.0
1002,sodales scelerisque mauris sit amet eros suspe...,582,0.136460,12.000000,4.0
1039,at ipsum ac tellus semper interdum mauris ulla...,70,0.050360,0.000000,3.0
1092,elit proin interdum mauris non ligula pellente...,46,0.029773,6.000000,0.0

In [13]:
df = df[~corrupted_mask].copy()
df.shape

(1168, 21)

In [14]:
pd.to_numeric(df['time'], errors='coerce').notna().sum()

np.int64(0)

## Issue 2: Missing values in `impressions`, `engagements`, `engagement rate`

In [15]:
df[df['impressions'].isnull()][['Tweet', 'time', 'impressions', 'engagements', 'engagement rate']]

,Tweet,time,impressions,engagements,engagement rate
414,mauris eget massa tempor convallis nulla neque...,white,NaN,NaN,NaN
514,in libero ut massa volutpat convallis morbi od...,Kind. —other daughter,NaN,NaN,NaN

In [16]:
df['impressions'] = df['impressions'].fillna(0)
df['engagements'] = df['engagements'].fillna(0)
df['engagement rate'] = df['engagement rate'].fillna(0)

In [17]:
df[['impressions', 'engagements', 'engagement rate']].isnull().sum()

impressions        0
engagements        0
engagement rate    0
dtype: int64

## Issue 3: Missing value in `retweets`

In [18]:
df[df['retweets'].isnull()][['Tweet', 'time', 'retweets']]

,Tweet,time,retweets
514,in libero ut massa volutpat convallis morbi od...,Kind. —other daughter,NaN

In [19]:
df['retweets'] = df['retweets'].fillna(0)

In [20]:
df['retweets'].isnull().sum()

np.int64(0)

## Issue 4: Missing values in `media views` and `media engagements`

In [21]:
df[['media views', 'media engagements']].isnull().sum()

media views          0
media engagements    0
dtype: int64

In [22]:
df['media views'] = df['media views'].fillna(0)
df['media engagements'] = df['media engagements'].fillna(0)

In [23]:
df[['media views', 'media engagements']].isnull().sum()

media views          0
media engagements    0
dtype: int64

## Final check — no missing values remain

In [24]:
df.isnull().sum()

Tweet                  0
id                     0
time                   0
impressions            0
engagements            0
engagement rate        0
retweets               0
replies                0
likes                  0
user profile clicks    0
url clicks             0
hashtag clicks         0
detail expands         0
permalink clicks       0
app opens              0
app installs           0
follows                0
email tweet            0
dial phone             0
media views            0
media engagements      0
dtype: int64

# Data Handling

## Duplicates — check by `id`

In [25]:
df.duplicated(subset=['id']).sum()

np.int64(0)

## Duplicates — check on all columns

In [26]:
df.duplicated().sum()

np.int64(0)

## Time zone conversion — UTC to IST (Asia/Kolkata)

In [27]:
df['time'].head()

0    2020-06-30 21:09 +0000
1    2020-06-30 17:14 +0000
2    2020-06-30 16:59 +0000
3    2020-06-30 13:55 +0000
4    2020-06-30 12:13 +0000
Name: time, dtype: object

In [28]:
df['time'] = pd.to_datetime(df['time'], format='mixed', errors='coerce', utc=True)

In [29]:
df['time_ist'] = df['time'].dt.tz_convert('Asia/Kolkata')

In [30]:
df[['time', 'time_ist']].head()

                       time                  time_ist
0 2020-06-30 21:09:00+00:00 2020-07-01 02:39:00+05:30
1 2020-06-30 17:14:00+00:00 2020-06-30 22:44:00+05:30
2 2020-06-30 16:59:00+00:00 2020-06-30 22:29:00+05:30
3 2020-06-30 13:55:00+00:00 2020-06-30 19:25:00+05:30
4 2020-06-30 12:13:00+00:00 2020-06-30 17:43:00+05:30

## Remove the 2 rows where `time_ist` is NaT (unparseable time values)

In [31]:
df[df['time_ist'].isnull()][['Tweet', 'time', 'time_ist']]

                                                 Tweet time time_ist
414  mauris eget massa tempor convallis nulla neque...  NaT      NaT
514  in libero ut massa volutpat convallis morbi od...  NaT      NaT

In [32]:
df = df.dropna(subset=['time_ist'])
df.shape

(1166, 22)

In [33]:
df['time_ist'].isnull().sum()

np.int64(0)

# Data Type Correction

## Check current dtypes — see which columns are still float

In [34]:
df.dtypes

Tweet                                        object
id                                            int64
time                            datetime64[ns, UTC]
impressions                                 float64
engagements                                 float64
engagement rate                             float64
retweets                                    float64
replies                                       int64
likes                                       float64
user profile clicks                         float64
url clicks                                    int64
hashtag clicks                                int64
detail expands                                int64
permalink clicks                              int64
app opens                                     int64
app installs                                  int64
follows                                       int64
email tweet                                   int64
dial phone                                    int64
media views                                 float64
media engagements                           float64
time_ist               datetime64[ns, Asia/Kolkata]
dtype: object

## Convert `impressions` from float to int

In [35]:
df['impressions'] = df['impressions'].astype(int)

In [36]:
df['impressions'].dtype

dtype('int64')

## Convert `engagements` from float to int

In [37]:
df['engagements'] = df['engagements'].astype(int)

In [38]:
df['engagements'].dtype

dtype('int64')

## Convert `retweets` from float to int

In [39]:
df['retweets'] = df['retweets'].astype(int)

In [40]:
df['retweets'].dtype

dtype('int64')

## Convert `likes` from float to int

In [41]:
df['likes'] = df['likes'].astype(int)

In [42]:
df['likes'].dtype

dtype('int64')

## Convert `user profile clicks` from float to int

In [43]:
df['user profile clicks'] = df['user profile clicks'].astype(int)

In [44]:
df['user profile clicks'].dtype

dtype('int64')

## Convert `media views` and `media engagements` from float to int

In [45]:
df['media views'] = df['media views'].astype(int)
df['media engagements'] = df['media engagements'].astype(int)

In [46]:
df[['media views', 'media engagements']].dtypes

media views          int64
media engagements    int64
dtype: object

## `engagement rate` stays float — it is a decimal fraction (e.g. 0.02 = 2%)

In [47]:
df['engagement rate'].dtype

dtype('float64')

## Final dtypes check — all columns correct

In [48]:
df.dtypes

Tweet                                        object
id                                            int64
time                            datetime64[ns, UTC]
impressions                                   int64
engagements                                   int64
engagement rate                             float64
retweets                                      int64
replies                                       int64
likes                                         int64
user profile clicks                           int64
url clicks                                    int64
hashtag clicks                                int64
detail expands                                int64
permalink clicks                              int64
app opens                                     int64
app installs                                  int64
follows                                       int64
email tweet                                   int64
dial phone                                    int64
media views                                   int64
media engagements                             int64
time_ist               datetime64[ns, Asia/Kolkata]
dtype: object

# Feature Creation

## `date_ist` — calendar date in IST

In [49]:
df['date_ist'] = df['time_ist'].dt.date
df['date_ist'].head()

0    2020-07-01
1    2020-06-30
2    2020-06-30
3    2020-06-30
4    2020-06-30
Name: date_ist, dtype: object

## `year_month` — year and month as a string (e.g. 2020-07)

In [50]:
df['year_month'] = df['time_ist'].dt.to_period('M').astype(str)
df['year_month'].value_counts().sort_index()

C:\Users\PREM\AppData\Local\Temp\ipykernel_16752\2599562986.py:1: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df['year_month'] = df['time_ist'].dt.to_period('M').astype(str)

year_month
2020-06    222
2020-07    308
2020-08    222
2020-09    230
2020-10    184
Name: count, dtype: int64

## `month_num` — month as a number (1 = January … 12 = December)

In [51]:
df['month_num'] = df['time_ist'].dt.month
df['month_num'].value_counts().sort_index()

month_num
6     222
7     308
8     222
9     230
10    184
Name: count, dtype: int64

## `month_name` — month as a full name (e.g. July)

In [52]:
df['month_name'] = df['time_ist'].dt.strftime('%B')
df['month_name'].value_counts()

month_name
July         308
September    230
June         222
August       222
October      184
Name: count, dtype: int64

## `day_of_month` — day number within the month (1 to 31)

In [53]:
df['day_of_month'] = df['time_ist'].dt.day
df['day_of_month'].describe()

count    1166.000000
mean       15.045455
std         9.151026
min         1.000000
25%         7.000000
50%        14.000000
75%        23.000000
max        31.000000
Name: day_of_month, dtype: float64

## `weekday_num` — day of week as a number (Monday = 1, Sunday = 7)

In [54]:
df['weekday_num'] = df['time_ist'].dt.weekday + 1
df['weekday_num'].value_counts().sort_index()

weekday_num
1    166
2    225
3    217
4    230
5    182
6     77
7     69
Name: count, dtype: int64

## `weekday_name` — day of week as a name (e.g. Monday)

In [55]:
df['weekday_name'] = df['time_ist'].dt.strftime('%A')
df['weekday_name'].value_counts()

weekday_name
Thursday     230
Tuesday      225
Wednesday    217
Friday       182
Monday       166
Saturday      77
Sunday        69
Name: count, dtype: int64

## `is_weekend` — True if Saturday or Sunday

In [56]:
df['is_weekend'] = df['weekday_num'].isin([6, 7])
df['is_weekend'].value_counts()

is_weekend
False    1020
True      146
Name: count, dtype: int64

## `hour_ist` — hour of the tweet in IST (0 to 23)

In [57]:
df['hour_ist'] = df['time_ist'].dt.hour
df['hour_ist'].value_counts().sort_index()

hour_ist
0      99
1      58
2      45
3      45
4      39
5      52
6      47
7      46
8      25
9      15
13      2
14      8
15     13
16     40
17     59
18     81
19     94
20     91
21     94
22     95
23    118
Name: count, dtype: int64

## `word_count` — number of words in the tweet

In [58]:
df['word_count'] = df['Tweet'].str.split().str.len()
df['word_count'].describe()

count    1166.000000
mean       26.075472
std         6.051096
min        16.000000
25%        21.000000
50%        26.000000
75%        31.000000
max        36.000000
Name: word_count, dtype: float64

## `char_count` — number of characters in the tweet

In [59]:
df['char_count'] = df['Tweet'].str.len()
df['char_count'].describe()

count    1166.000000
mean      167.722127
std        39.764284
min        80.000000
25%       134.000000
50%       167.000000
75%       200.750000
max       259.000000
Name: char_count, dtype: float64

## `has_D_upper` — True if tweet contains uppercase letter D (case-sensitive)

In [60]:
df['has_D_upper'] = df['Tweet'].str.contains('D', regex=False)
df['has_D_upper'].value_counts()

has_D_upper
False    1166
Name: count, dtype: int64

## `has_H_upper` — True if tweet contains uppercase letter H (case-sensitive)

In [61]:
df['has_H_upper'] = df['Tweet'].str.contains('H', regex=False)
df['has_H_upper'].value_counts()

has_H_upper
False    1166
Name: count, dtype: int64

## `has_media` — True if media views > 0

In [62]:
df['has_media'] = df['media views'] > 0
df['has_media'].value_counts()

has_media
False    731
True     435
Name: count, dtype: int64

## `has_link` — True if url clicks > 0

In [63]:
df['has_link'] = df['url clicks'] > 0
df['has_link'].value_counts()

has_link
False    947
True     219
Name: count, dtype: int64

## `has_hashtag` — True if hashtag clicks > 0

In [64]:
df['has_hashtag'] = df['hashtag clicks'] > 0
df['has_hashtag'].value_counts()

has_hashtag
False    1074
True       92
Name: count, dtype: int64

## `has_app_open` — True if app opens > 0

In [65]:
df['has_app_open'] = df['app opens'] > 0
df['has_app_open'].value_counts()

has_app_open
False    1164
True        2
Name: count, dtype: int64

## `media_label` — readable label for has_media

In [66]:
df['media_label'] = df['has_media'].map({True: 'With Media', False: 'Without Media'})
df['media_label'].value_counts()

media_label
Without Media    731
With Media       435
Name: count, dtype: int64

## `app_open_label` — readable label for has_app_open

In [67]:
df['app_open_label'] = df['has_app_open'].map({True: 'With App Opens', False: 'Without App Opens'})
df['app_open_label'].value_counts()

app_open_label
Without App Opens    1164
With App Opens          2
Name: count, dtype: int64

## `category` — Media first, then Links, then Hashtags, else Text Only

In [68]:
df['category'] = 'Text Only'
df.loc[df['has_hashtag'], 'category'] = 'Hashtags'
df.loc[df['has_link'],    'category'] = 'Links'
df.loc[df['has_media'],   'category'] = 'Media'
df['category'].value_counts()

category
Text Only    622
Media        435
Links         74
Hashtags      35
Name: count, dtype: int64

## `rt_plus_likes` — sum of retweets and likes

In [69]:
df['rt_plus_likes'] = df['retweets'] + df['likes']
df['rt_plus_likes'].describe()

count    1166.000000
mean        7.164666
std        78.069389
min         0.000000
25%         1.000000
50%         2.000000
75%         5.000000
max      2652.000000
Name: rt_plus_likes, dtype: float64

## Final column count after all features added

In [70]:
df.shape

(1166, 43)

# Data Analysis

Which month had the highest total impressions?

In [71]:
df.groupby('year_month')['impressions'].sum().sort_index()

year_month
2020-06    132338
2020-07    345286
2020-08    157796
2020-09    175053
2020-10    101225
Name: impressions, dtype: int64

July 2020 had by far the most impressions (345,286), nearly double any other month.

Which tweet category has the highest average engagement rate?

In [72]:
df.groupby('category')['engagement rate'].mean().round(4).sort_values(ascending=False)

category
Links        0.0597
Media        0.0515
Hashtags     0.0297
Text Only    0.0234
Name: engagement rate, dtype: float64

Link tweets have the highest avg engagement rate (5.97%), followed by Media (5.15%) — Text Only is lowest (2.34%).

Which day of the week gets the most retweets?

In [73]:
df.groupby('weekday_name')['retweets'].sum().sort_values(ascending=False)

weekday_name
Friday       202
Monday        80
Wednesday     61
Tuesday       54
Thursday      40
Saturday      20
Sunday        14
Name: retweets, dtype: int64

Friday dominates with 202 total retweets — nearly 4x more than any other day.

Do weekend tweets get a higher engagement rate than weekday tweets?

In [74]:
df.groupby('is_weekend')['engagement rate'].mean().round(4)

is_weekend
False    0.0355
True     0.0424
Name: engagement rate, dtype: float64

Weekend tweets have a slightly higher avg engagement rate (4.24%) than weekday tweets (3.55%).

What are the top 10 tweets by combined retweets and likes?

In [75]:
df.nlargest(10, 'rt_plus_likes')[['Tweet', 'rt_plus_likes', 'retweets', 'likes']]

,Tweet,rt_plus_likes,retweets,likes
441,elementum ligula vehicula consequat morbi a ip...,2652,165,2487
623,accumsan felis ut at dolor quis odio consequat...,137,0,137
541,justo in hac habitasse platea dictumst etiam f...,88,5,83
749,lectus aliquam sit amet diam in magna bibendum...,68,3,65
545,congue eget semper rutrum nulla nunc purus pha...,64,15,49
1139,nam dui proin leo odio porttitor id consequat ...,62,1,61
816,bibendum imperdiet nullam orci pede venenatis ...,59,5,54
1093,molestie hendrerit at vulputate vitae nisl aen...,59,1,58
880,sit amet lobortis sapien sapien non mi integer...,55,3,52
431,vestibulum sagittis sapien cum sociis natoque ...,54,1,53

The top tweet has 2,652 rt_plus_likes (165 retweets + 2,487 likes), far ahead of all others.

Do tweets with media get a higher engagement rate than tweets without media?

In [76]:
df.groupby('media_label')['engagement rate'].mean().round(4)

media_label
With Media       0.0515
Without Media    0.0274
Name: engagement rate, dtype: float64

Tweets with media have an avg engagement rate of 5.15% vs 2.74% without media — nearly double.

At what hour (IST) are tweets most commonly posted?

In [77]:
df.groupby('hour_ist')['id'].count().sort_index()

hour_ist
0      99
1      58
2      45
3      45
4      39
5      52
6      47
7      46
8      25
9      15
13      2
14      8
15     13
16     40
17     59
18     81
19     94
20     91
21     94
22     95
23    118
Name: id, dtype: int64

Most tweets are posted late night (11 PM = 118 tweets) and midnight (12 AM = 99 tweets) IST. Hours 9-12 have almost no tweets.

Which category drives the most total user interactions (url + profile + hashtag clicks)?

In [78]:
df['total_clicks'] = df['url clicks'] + df['user profile clicks'] + df['hashtag clicks']
df.groupby('category')['total_clicks'].sum().sort_values(ascending=False)

category
Media        2603
Links        1937
Text Only     800
Hashtags      360
Name: total_clicks, dtype: int64

Media tweets generate the most clicks (2,603), followed by Links (1,937) — Hashtag tweets are lowest despite having a dedicated click type.

How does the average engagement rate change across months?

In [79]:
df.groupby('year_month')['engagement rate'].mean().round(4).sort_index()

year_month
2020-06    0.0347
2020-07    0.0362
2020-08    0.0344
2020-09    0.0388
2020-10    0.0382
Name: engagement rate, dtype: float64

Engagement rate is fairly stable across months (3.4%-3.9%), with September and October slightly higher.

Is there a difference in average word count across tweet categories?

In [80]:
df.groupby('category')['word_count'].mean().round(1).sort_values(ascending=False)

category
Hashtags     26.2
Media        26.1
Text Only    26.0
Links        25.9
Name: word_count, dtype: float64

All categories have nearly identical average word counts (~26 words), so tweet length does not explain engagement differences.

# Filter Check

## Filter 1 — Tweet Interaction Breakdown: even day, word_count > 40, any click > 0

In [81]:
f1 = df[
    (df['day_of_month'] % 2 == 0) &
    (df['word_count'] > 40) &
    (df['total_clicks'] > 0)
]
print('Rows matching Filter 1:', len(f1))
print('Note: max word_count in dataset is', df['word_count'].max(), '— filter requires > 40, so 0 rows match.')

Rows matching Filter 1: 0
Note: max word_count in dataset is 36 — filter requires > 40, so 0 rows match.

## Filter 2 — Engagement Rate Comparison: weekday, hour 9-16, even impressions, odd day, char > 30, no uppercase D

In [82]:
f2 = df[
    (~df['is_weekend']) &
    (df['hour_ist'] >= 9) & (df['hour_ist'] <= 16) &
    (df['impressions'] % 2 == 0) &
    (df['day_of_month'] % 2 != 0) &
    (df['char_count'] > 30) &
    (~df['has_D_upper'])
]
print('Rows matching Filter 2:', len(f2))

Rows matching Filter 2: 14

## Filter 3 — Media Interaction by Day: months 7-9, even impressions, odd day, char > 30, no uppercase H

In [83]:
f3 = df[
    (df['month_num'] >= 7) & (df['month_num'] <= 9) &
    (df['impressions'] % 2 == 0) &
    (df['day_of_month'] % 2 != 0) &
    (df['char_count'] > 30) &
    (~df['has_H_upper'])
]
print('Rows matching Filter 3:', len(f3))

Rows matching Filter 3: 214

## Filter 4 — Replies, Retweets, Likes: months 6-8 (June, July, August)

In [84]:
f4 = df[
    (df['month_num'] >= 6) & (df['month_num'] <= 8)
]
print('Rows matching Filter 4:', len(f4))

Rows matching Filter 4: 752

## Filter 5 — Top 10 Tweets: weekday, even impressions, odd day, word_count < 30

In [85]:
f5 = df[
    (~df['is_weekend']) &
    (df['impressions'] % 2 == 0) &
    (df['day_of_month'] % 2 != 0) &
    (df['word_count'] < 30)
]
print('Rows matching Filter 5:', len(f5))

Rows matching Filter 5: 187

# Saving Cleaned Data

## Strip timezone from `time_ist` so Power BI reads it as a plain datetime

In [86]:
df['time_ist'] = df['time_ist'].dt.tz_localize(None)
df['time_ist'].head()

0   2020-07-01 02:39:00
1   2020-06-30 22:44:00
2   2020-06-30 22:29:00
3   2020-06-30 19:25:00
4   2020-06-30 17:43:00
Name: time_ist, dtype: datetime64[ns]

## Final shape and column list before saving

In [87]:
df.shape

(1166, 44)

In [88]:
df.columns.tolist()

['Tweet',
 'id',
 'time',
 'impressions',
 'engagements',
 'engagement rate',
 'retweets',
 'replies',
 'likes',
 'user profile clicks',
 'url clicks',
 'hashtag clicks',
 'detail expands',
 'permalink clicks',
 'app opens',
 'app installs',
 'follows',
 'email tweet',
 'dial phone',
 'media views',
 'media engagements',
 'time_ist',
 'date_ist',
 'year_month',
 'month_num',
 'month_name',
 'day_of_month',
 'weekday_num',
 'weekday_name',
 'is_weekend',
 'hour_ist',
 'word_count',
 'char_count',
 'has_D_upper',
 'has_H_upper',
 'has_media',
 'has_link',
 'has_hashtag',
 'has_app_open',
 'media_label',
 'app_open_label',
 'category',
 'rt_plus_likes',
 'total_clicks']

## Save to CSV

In [89]:
df.to_csv('../data/processed/twitter_cleaned.csv', index=False)

## Verify the saved file — reload and check shape

In [90]:
check = pd.read_csv('../data/processed/twitter_cleaned.csv')
check.shape

(1166, 44)

In [91]:
check.head()

,Tweet,id,time,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,...,has_H_upper,has_media,has_link,has_hashtag,has_app_open,media_label,app_open_label,category,rt_plus_likes,total_clicks
0,id ligula suspendisse ornare consequat lectus ...,6672567125560790,2020-06-30 21:09:00+00:00,365,4,0.010959,0,0,1,2,...,False,False,False,False,False,Without Media,Without App Opens,Text Only,1,2
1,euismod scelerisque quam turpis adipiscing lor...,8265456713789040,2020-06-30 17:14:00+00:00,184,2,0.010870,0,0,2,0,...,False,False,False,False,False,Without Media,Without App Opens,Text Only,2,0
2,leo rhoncus sed vestibulum sit amet cursus id ...,281117346800427,2020-06-30 16:59:00+00:00,2644,46,0.017398,1,1,17,0,...,False,True,True,False,False,With Media,Without App Opens,Media,18,3
3,aenean lectus pellentesque eget nunc donec qui...,7758025943576750,2020-06-30 13:55:00+00:00,301,3,0.009967,0,1,2,0,...,False,False,False,False,False,Without Media,Without App Opens,Text Only,2,0
4,sed accumsan felis ut at dolor quis odio conse...,6131837006729570,2020-06-30 12:13:00+00:00,528,0,0.000000,0,0,0,0,...,False,False,False,False,False,Without Media,Without App Opens,Text Only,0,0